#!/usr/bin/env python3
"""Transactional reference refresh; stdlib only. No writes until all fetches parse."""
import argparse
from datetime import datetime, timezone
import hashlib
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
import shutil
import tempfile
import urllib.parse
import urllib.request

from docc2md import render as render_docc
from transcript import render as render_transcript

APPLE = 'https://developer.apple.com'
DEFAULT = Path(__file__).resolve().parents[2] / 'Apple-Style-HIG/reference'


def digest(data):
    return hashlib.sha256(data).hexdigest()


class DesignHTML(HTMLParser):
    """Only main/article content; fail closed on unfamiliar page structure."""
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.depth = 0
        self.skip = 0
        self.out = []
        self.links = []
        self.has_title = False

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag in ('main', 'article'):
            self.depth += 1
        if not self.depth:
            return
        if tag in ('script', 'style', 'nav'):
            self.skip += 1
        if self.skip:
            return
        if re.fullmatch(r'h[1-6]', tag):
            self.out.append('\n\n' + '#' * int(tag[1]) + ' ')
            self.has_title |= tag == 'h1'
        elif tag in ('p', 'div', 'section', 'br'):
            self.out.append('\n')
        elif tag == 'li':
            self.out.append('\n- ')
        elif tag == 'a':
            href = urllib.parse.urljoin(APPLE, attrs.get('href', ''))
            self.links.append(href if href.startswith(('https://', 'http://')) else '')
            self.out.append('[')
        elif tag == 'img' and attrs.get('alt'):
            self.out.append('[Image: ' + attrs['alt'] + ']')

    def handle_endtag(self, tag):
        if not self.depth:
            return
        if tag in ('script', 'style', 'nav') and self.skip:
            self.skip -= 1
        elif not self.skip:
            if tag == 'a' and self.links:
                href = self.links.pop()
                self.out.append('](' + href + ')' if href else ']')
            elif tag in ('p', 'li') or re.fullmatch(r'h[1-6]', tag):
                self.out.append('\n')
        if tag in ('main', 'article'):
            self.depth -= 1

    def handle_data(self, data):
        if self.depth and not self.skip:
            self.out.append(re.sub(r'\s+', ' ', data))


def render_html(source):
    parser = DesignHTML()
    parser.feed(source)
    content = re.sub(r'\n[ \t]+', '\n', ''.join(parser.out))
    content = '\n'.join(line.rstrip() for line in content.splitlines())
    content = re.sub(r'\n{3,}', '\n\n', content).strip()
    if not parser.has_title or len(content) < 80:
        raise ValueError('Design page has no substantial main/article content with h1')
    return content + '\n'


def fetch(url):
    request = urllib.request.Request(url, headers={'User-Agent': 'Apple-Style-reference-updater/1'})
    with urllib.request.urlopen(request, timeout=30) as response:
        if response.status != 200:
            raise ValueError(f'HTTP {response.status}: {url}')
        data = response.read(10_000_001)
        if len(data) > 10_000_000:
            raise ValueError('Response exceeds 10 MB')
        return data


def validate_source(source):
    path = Path(source['path'])
    if path.is_absolute() or '..' in path.parts or path.suffix != '.md' or path.parts[0] not in ('hig', 'liquid-glass', 'design-site', 'wwdc25'):
        raise ValueError(f'Unsafe reference path: {path}')
    for key in ('url', 'fetch_url'):
        url = urllib.parse.urlparse(source[key])
        if url.scheme != 'https' or url.netloc != 'developer.apple.com':
            raise ValueError(f'Unexpected source origin: {source[key]}')
    if source['kind'] not in ('docc', 'html', 'transcript'):
        raise ValueError('Unknown source kind')


def index(reference, sources):
    lines = ['# Apple design reference index', '', 'Generated by update-reference.sh; provenance and SHA-256: [sources.json](sources.json).', 'Legacy timestamps marked null are unknown, not freshly fetched.', '']
    for category in ('hig', 'liquid-glass', 'design-site', 'wwdc25'):
        lines += ['## ' + category, '']
        for source in sorted(sources, key=lambda x: x['path']):
            if not source['path'].startswith(category + '/'):
                continue
            path = reference / source['path']
            if path.exists():
                title = next((line.lstrip('# ').strip() for line in path.read_text(encoding='utf-8').splitlines() if line.startswith('# ')), path.stem)
                lines.append(f"- [{title}]({source['path']}) · [Source]({source['url']})")
        lines.append('')
    return '\n'.join(lines)


def update(reference=DEFAULT, only=(), limit=None, discover=True, fetcher=fetch):
    reference = Path(reference).resolve()
    report = {'started_at': datetime.now(timezone.utc).isoformat(), 'applied': False, 'added': [], 'modified': [], 'unchanged': [], 'failed': [], 'recheck_cheatsheets': []}
    manifest = json.loads((reference / 'sources.json').read_text(encoding='utf-8'))
    sources = manifest['sources']
    for source in sources:
        validate_source(source)
    if len({s['path'] for s in sources}) != len(sources):
        raise ValueError('Duplicate source paths')
    if only and set(only) - {s['path'] for s in sources}:
        raise ValueError('Unknown --only path')
    queue = [s for s in sources if not only or s['path'] in only]
    if limit is not None:
        queue = queue[:limit]
    known = {s['url'] for s in sources}
    staged = {}
    for source in queue:
        try:
            payload = fetcher(source['fetch_url'])
            text = payload.decode('utf-8')
            if source['kind'] == 'docc':
                doc = json.loads(text)
                rendered = render_docc(doc) + '\n'
                if discover and not only and limit is None:
                    for item in doc.get('references', {}).values():
                        url = item.get('url', '').split('#')[0]
                        if url.startswith('/design/human-interface-guidelines/'):
                            canonical = APPLE + url
                            slug = url.rsplit('/', 1)[1]
                            if canonical not in known and re.fullmatch(r'[a-z0-9-]+', slug):
                                new = {'path': f'hig/{slug}.md', 'kind': 'docc', 'url': canonical, 'fetch_url': APPLE + '/tutorials/data' + url + '.json', 'fetched_at': None, 'sha256': None}
                                validate_source(new)
                                sources.append(new); queue.append(new); known.add(canonical)
            else:
                rendered = (render_transcript if source['kind'] == 'transcript' else render_html)(text)
            data = rendered.encode('utf-8')
            path = reference / source['path']
            if path.is_symlink() or any(p.is_symlink() for p in path.parents if p != reference.parent):
                raise ValueError('Reference path is a symbolic link')
            old = path.read_bytes() if path.exists() else None
            report['added' if old is None else 'unchanged' if old == data else 'modified'].append(source['path'])
            staged[source['path']] = data
            source.update(fetched_at=datetime.now(timezone.utc).isoformat(), sha256=digest(data), source_sha256=digest(payload), provenance='fetched')
        except Exception as error:
            report['failed'].append({'path': source['path'], 'url': source['url'], 'error': f'{type(error).__name__}: {error}'})
    if report['added'] or report['modified']:
        report['recheck_cheatsheets'] = ['skills/Apple-Style/cheatsheets/' + x for x in ('design-principles.md','materials-and-liquid-glass.md','color.md','typography.md','layout-and-shapes.md','components-quickref.md','motion-and-interaction.md','accessibility-and-inclusion.md','web-implementation.md')]
    if report['failed']:
        return report  # all-or-nothing batch: valid local pages are untouched
    stage = Path(tempfile.mkdtemp(prefix='.reference-stage-', dir=reference.parent))
    backup = stage / 'previous'
    candidate = stage / 'next'
    try:
        shutil.copytree(reference, candidate, symlinks=True)
        for path, data in staged.items():
            dest = candidate / path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
        (candidate / 'sources.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        (candidate / 'INDEX.md').write_text(index(candidate, sources), encoding='utf-8')
        os.replace(reference, backup)
        try:
            os.replace(candidate, reference)
        except BaseException:
            os.replace(backup, reference)
            raise
        report['applied'] = True
    finally:
        # Keep recoverable previous data if rollback itself failed.
        if reference.exists():
            shutil.rmtree(stage)
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reference', type=Path, default=DEFAULT)
    parser.add_argument('--only', action='append', default=[], help='exact manifest path; repeatable')
    parser.add_argument('--limit', type=int, help='bounded online validation; disables discovery')
    parser.add_argument('--no-discover', action='store_true')
    parser.add_argument('--index-only', action='store_true', help='regenerate index from local files; no fetching')
    parser.add_argument('--report', type=Path, default=Path('reference-update-report.json'))
    args = parser.parse_args()
    if args.limit is not None and args.limit < 1:
        parser.error('--limit must be positive')
    lock = args.reference.parent / '.reference-update.lock'
    with lock.open('x') as handle:
        handle.write(str(os.getpid()))
    try:
        if args.index_only:
            sources = json.loads((args.reference / 'sources.json').read_text(encoding='utf-8'))['sources']
            temporary = args.reference / 'INDEX.md.tmp'
            temporary.write_text(index(args.reference, sources), encoding='utf-8')
            temporary.replace(args.reference / 'INDEX.md')
            return 0
        report = update(args.reference, args.only, args.limit, not args.no_discover)
        args.report.parent.mkdir(parents=True, exist_ok=True)
        temporary = args.report.with_suffix('.tmp')
        temporary.write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        temporary.replace(args.report)
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 1 if report['failed'] else 0
    finally:
        lock.unlink()


if __name__ == '__main__':
    raise SystemExit(main())
